### ISSUE TITLE
 external session storage does not work

### ISSUE THREAD

**Issue by ddtramp** [rkusa/koa-passport#123] opened 2018-11-16 10:12 UTC
use redis for session storage

**Comment by rkusa** [comment] 2018-11-26 07:48
Hi, have you confirmed that it is a `koa-passport` and not a `passport` issue? Also some more information / examples would be helpful.

**Comment by rkusa** [comment] 2018-12-11 07:34
Closing as duplicate of #118

**Closed by rkusa** 2018-12-11 07:34 UTC
